name: Java CI

on:
  push:
    branches: ["releases"]
  pull_request:
    branches: ["releases"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Prepare build Maven
        run: Set-ExecutionPolicy -Scope Process $policy
      - name: Build with Maven
        run: mvn -B package --file pom.xml